### PR TITLE
Add support for async handlers

### PR DESCRIPTION
**Pull request by natanrolnik**
This PR adds support for async handlers - the caller must call the received `completion()` block with the result. If you think it should be designed differently, let's discuss 😄

### CODE REVIEW

**Comment by tonisuter** [comment]
Hi Natan, thanks! I'll have to look at it in more detail on the weekend before I merge it but I think this looks great!

**Comment by tonisuter** [comment]
Thanks again for this pull request! After I merge it, I want to add a usage example for async handlers. Here's what I have come up with so far:

```swift
import AWSLambdaSwift
import Foundation

struct Event: Codable {
    let countryCode: String
}

struct Country: Codable {
    let name: String
    let capital: String
    let population: Int
}

struct Result: Codable {
    let country: Country?
}

func fetchCountry(event: Event, context: Context, completionHandler: @escaping (Result) -> Void) {
    guard let url = URL(string: "http://restcountries.eu/rest/v2/alpha/\(event.countryCode)") else {
        completionHandler(Result(country: nil))
        return
    }

    let session = URLSession(configuration: .default)
    let dataTask = session.dataTask(with: url) { data, response, error in
        guard error == nil, let data = data else {
            completionHandler(Result(country: nil))
            return
        }

        let jsonDecoder = JSONDecoder()
        guard let country = try? jsonDecoder.decode(Country.self, from: data) else {
            completionHandler(Result(country: nil))
            return
        }

        completionHandler(Result(country: country))
    }
    dataTask.resume()
}

let runtime = try Runtime()
runtime.registerLambda("fetchCountry", handlerFunction: fetchCountry)
try runtime.start()
```

Do you think this makes sense? Or do you have a better example?

**Comment by natanrolnik** [comment]
Yes, looks good! I would just avoid calling it `Result` due to the type that is coming in Swift 5, with the same name. Maybe `Output` or something in this direction?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tonisuter** [comment]
Yeah, that makes sense!

**Pull request merged**
